### ISSUE TITLE
atom plugin pls

### ISSUE THREAD

**Issue by dasilvacontin** [dasilvacontin/contrib-rocket#5]

**Comment by tofumarinado** [comment]
[( ͡° ͜ʖ ͡°)](https://github.com/wextia/atom-contrib-rocket)

**Comment by dasilvacontin** [comment]
I don't care much about making an atom plugin, maybe a VSCode one. :)

**Comment by tofumarinado** [comment]
But... but... i maed dis :cry: :disappointed:

**Comment by dasilvacontin** [comment]
Oh sorry, I didn't notice the link

**Comment by dasilvacontin** [comment]
Closing, I don't use Atom anymore.
